# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: docker build -t exo:6.3 .' # runs during prebuild
    command: docker run -e EXO_DB_PASSWORD=admin exo:1.0

ports:
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
